remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme 

show_downloads: false
title: "Hemashree M S"
description: "I am a second year student currently pursuing Computer Science and Engineering @ PES University RR Campus. I like learning new things, gaining experience and interacting with diverse group of people. I am always open to new opportunities to gain knowledge and skills."
